# Configuration for precompute pipeline

# Features to extract
features:
  - cotracker
  # - depth
  # - flow

# CoTracker settings
cotracker:
  window_size: 48
  interval: 10
  initialization_method: grid  # Options: grid, sift, superpoint
  grid_size: 20
  device: cuda

# Depth estimation settings (future)
depth:
  model: geometrycrafter
  device: cuda

# Optical flow settings (future)
optical_flow:
  model: raft
  device: cuda

# Visualization settings
visualization:
  enabled: true          # Enable visualization after extraction
  save_video: true       # Save MP4 video
  save_frames: true      # Save sample frames
  fps: 10               # Output video FPS
  point_size: 6         # Size of tracked points
  trail_length: 20      # Length of motion trails

# Preprocessing settings
preprocessing:
  enabled: false         # Enable preprocessing before feature extraction
  target_width: 1920    # Target width for resized images
  target_height: 1080   # Target height for resized images
  force_overwrite: false # Overwrite existing preprocessed data

# General settings
log_level: INFO