# Configuration for precompute pipeline with SIFT initialization

# Features to extract
features:
  - cotracker
  # - depth
  # - flow

# CoTracker settings with SIFT initialization
cotracker:
  window_size: 48
  interval: 10
  initialization_method: sift  # Using SIFT feature detection
  max_features: 400           # Maximum SIFT features per window
  grid_size: 20               # Not used for SIFT, but kept for compatibility
  device: cuda

# Depth estimation settings (future)
depth:
  model: geometrycrafter
  device: cuda

# Optical flow settings (future)
optical_flow:
  model: raft
  device: cuda

# Visualization settings
visualization:
  enabled: true          # Enable visualization after extraction
  save_video: true       # Save MP4 video
  save_frames: true      # Save sample frames
  fps: 10               # Output video FPS
  point_size: 6         # Size of tracked points
  trail_length: 20      # Length of motion trails

# Preprocessing settings
preprocessing:
  enabled: true          # Enable preprocessing before feature extraction
  target_width: 1024    # Target width for resized images
  target_height: 576   # Target height for resized images
  force_overwrite: false # Overwrite existing preprocessed data

# General settings
log_level: INFO