# Test configuration for quick testing
# Small windows and grids for fast processing

# Features to extract
features:
  - cotracker

# CoTracker settings for testing
cotracker:
  window_size: 24      # Small window
  interval: 12         # 50% overlap
  initialization_method: grid
  grid_size: 10        # Small grid (10x10 = 100 points)
  device: cuda

# Visualization settings
visualization:
  enabled: true         # Always visualize for testing
  save_video: true
  save_frames: true     # Save all outputs for testing
  fps: 5                # Lower FPS for quick preview
  point_size: 6
  trail_length: 10      # Short trails for testing

# Preprocessing settings
preprocessing:
  enabled: true          # Enable preprocessing before feature extraction
  target_width: 1920    # Target width for resized images
  target_height: 1080   # Target height for resized images
  force_overwrite: false # Overwrite existing preprocessed data

# General settings
log_level: DEBUG  # Verbose logging for testing