# Sparse tracking configuration
# Fewer windows with larger intervals for faster processing

# Features to extract
features:
  - cotracker

# CoTracker settings for sparse tracking
cotracker:
  window_size: 64      # Larger windows
  interval: 32         # Large interval = sparse coverage
  initialization_method: sift  # Use SIFT for better feature selection
  grid_size: 15        # Not used for SIFT, but fallback grid size
  device: cuda

# Visualization settings
visualization:
  enabled: true
  save_video: true
  save_frames: true     # Save frames for sparse tracking
  fps: 10
  point_size: 8         # Larger points for visibility
  trail_length: 30      # Longer trails for sparse windows

# Preprocessing settings
preprocessing:
  enabled: true          # Enable preprocessing before feature extraction
  target_width: 1920    # Target width for resized images
  target_height: 1080   # Target height for resized images
  force_overwrite: false # Overwrite existing preprocessed data

# General settings
log_level: INFO