# Window-based Bundle Adjustment Configuration
# Following GeometryCrafter's approach

device: cuda  # cuda or cpu

# Track loading configuration
track_loader:
  track_mode: "sift"  # Options: sift, superpoint, grid
  depth_subdir: "depth/GeometryCrafter"  # Subdirectory for depth maps

# Optimization configuration
optimization:
  # Phase 1: Camera-only optimization
  max_iterations: 10000
  learning_rate_camera: 0.001  # For quaternion rotations
  learning_rate_translation: 0.01  # For translations
  learning_rate_fov: 0.0001  # For FOV parameters
  
  # Phase 2: Joint optimization (if --use_refine)
  learning_rate_3d: 0.01  # For 3D points
  
  # Convergence
  convergence_threshold: 1.0e-6
  gradient_clip: 1.0
  
  # Robust loss
  use_robust_loss: true
  robust_loss_sigma: 1.0  # Huber loss threshold
  
  # Loss weights
  proj_loss_weight: 1.0  # Weight for reprojection loss
  depth_loss_weight: 0.0  # Weight for depth consistency (GeometryCrafter default: 0)

# Output configuration
output:
  save_intermediate: true  # Save Phase 1 results separately
  save_colmap: true  # Export to COLMAP format
  colmap_format: binary  # binary or text

# Camera initialization
camera:
  # Image dimensions
  image_width: 1024
  image_height: 576
  
  # Single camera mode (all frames share same intrinsics)
  single_camera: true  # If true, FOV is shared across all frames
  
  # Initial FOV if intrinsics not available
  default_fov_degrees: 60

# Visualization settings
visualization:
  enabled: true  # Generate visualization plots
  # All plots are saved as PNG files for CLI environments